// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBooksDO = "books"

// BooksDO 书籍表
type BooksDO struct {
	ID          int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Title       string     `gorm:"column:title;type:varchar(128);not null;comment:书籍名称" json:"title"`                 // 书籍名称
	Author      string     `gorm:"column:author;type:varchar(128);not null;comment:作者" json:"author"`                 // 作者
	Price       int32      `gorm:"column:price;type:int;not null;comment:价格" json:"price"`                            // 价格
	PublishDate time.Time  `gorm:"column:publish_date;type:datetime;not null;comment:出版日期" json:"publish_date"`       // 出版日期
	Users       []*UsersDO `gorm:"foreignKey:ID;joinForeignKey:BookID;joinReferences:UserID;many2many:user_books;references:ID" json:"users"`
}

// TableName BooksDO's table name
func (*BooksDO) TableName() string {
	return TableNameBooksDO
}
