// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserBooksDO = "user_books"

// UserBooksDO 用户书籍关联表
type UserBooksDO struct {
	UserID     int64     `gorm:"column:user_id;type:bigint unsigned;not null;comment:用户ID" json:"user_id"`                            // 用户ID
	BookID     int64     `gorm:"column:book_id;type:bigint unsigned;not null;comment:书籍ID" json:"book_id"`                            // 书籍ID
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	ID         int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
}

// TableName UserBooksDO's table name
func (*UserBooksDO) TableName() string {
	return TableNameUserBooksDO
}
