// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUsersDO = "users"

// UsersDO 用户表
type UsersDO struct {
	ID         int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                   // 主键
	Name       string     `gorm:"column:name;type:varchar(64);not null;comment:用户名" json:"name"`                                       // 用户名
	Password   string     `gorm:"column:password;type:varchar(128);not null;comment:密码" json:"password"`                               // 密码
	CreateTime time.Time  `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	Status     int32      `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态：1-正常，0-禁用" json:"status"`           // 状态：1-正常，0-禁用
	Books      []*BooksDO `gorm:"foreignKey:ID;joinForeignKey:UserID;joinReferences:BookID;many2many:user_books;references:ID" json:"books"`
}

// TableName UsersDO's table name
func (*UsersDO) TableName() string {
	return TableNameUsersDO
}
