// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmRuleChannelsDO = "alarm_rule_channels"

// AlarmRuleChannelsDO mapped from table <alarm_rule_channels>
type AlarmRuleChannelsDO struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                 // 自增id
	RuleID     int64      `gorm:"column:rule_id;type:bigint;not null;comment:规则id" json:"rule_id"`                            // 规则id
	ChannelID  int64      `gorm:"column:channel_id;type:bigint;not null;comment:渠道id" json:"channel_id"`                      // 渠道id
	CreateTime *time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName AlarmRuleChannelsDO's table name
func (*AlarmRuleChannelsDO) TableName() string {
	return TableNameAlarmRuleChannelsDO
}
