// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmChannelsDO = "alarm_channels"

// AlarmChannelsDO mapped from table <alarm_channels>
type AlarmChannelsDO struct {
	ID         int64           `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                                    // 自增id
	TenantID   int64           `gorm:"column:tenant_id;type:bigint;not null;uniqueIndex:uni_tid_pid_name,priority:1;comment:租户ID" json:"tenant_id"`   // 租户ID
	ProjectID  int64           `gorm:"column:project_id;type:bigint;not null;uniqueIndex:uni_tid_pid_name,priority:2;comment:项目ID" json:"project_id"` // 项目ID
	Name       string          `gorm:"column:name;type:varchar(255);not null;uniqueIndex:uni_tid_pid_name,priority:3" json:"name"`
	Groups     string          `gorm:"column:groups;type:text;not null;comment:渠道信息" json:"groups"`         // 渠道信息
	Mod        int32           `gorm:"column:mod;type:int;not null;comment:外部可见" json:"mod"`                // 外部可见
	IsDeleted  int32           `gorm:"column:is_deleted;type:int;not null;comment:是否被删除" json:"is_deleted"` // 是否被删除
	CreatedBy  string          `gorm:"column:created_by;type:varchar(50);not null" json:"created_by"`
	CreateTime *time.Time      `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime *time.Time      `gorm:"column:update_time;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	Rules      []*AlarmRulesDO `gorm:"foreignKey:ID;joinForeignKey:ChannelID;joinReferences:RuleID;many2many:alarm_rule_channels;references:ID" json:"rules"`
}

// TableName AlarmChannelsDO's table name
func (*AlarmChannelsDO) TableName() string {
	return TableNameAlarmChannelsDO
}
