// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmRulesDO = "alarm_rules"

// AlarmRulesDO mapped from table <alarm_rules>
type AlarmRulesDO struct {
	ID               int64              `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增id" json:"id"` // 自增id
	ModuleID         int64              `gorm:"column:module_id;type:bigint;not null;comment:模块id" json:"module_id"`        // 模块id
	TemplateID       int64              `gorm:"column:template_id;type:bigint;not null;comment:模板id" json:"template_id"`    // 模板id
	TenantID         int64              `gorm:"column:tenant_id;type:bigint;not null;comment:租户ID" json:"tenant_id"`        // 租户ID
	ProjectID        int64              `gorm:"column:project_id;type:bigint;not null;comment:项目ID" json:"project_id"`      // 项目ID
	Name             string             `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Tags             *string            `gorm:"column:tags;type:varchar(255);comment:用户添加的标签" json:"tags"`                           // 用户添加的标签
	SysTags          string             `gorm:"column:sys_tags;type:json;not null;comment:系统添加的标签" json:"sys_tags"`                  // 系统添加的标签
	Config           string             `gorm:"column:config;type:text;not null;comment:规则" json:"config"`                           // 规则
	Level            string             `gorm:"column:level;type:varchar(50);not null;comment:级别" json:"level"`                      // 级别
	State            string             `gorm:"column:state;type:varchar(25);not null;default:going_online;comment:状态" json:"state"` // 状态
	RuntimeConfig    string             `gorm:"column:runtime_config;type:json;not null;comment:运行配置" json:"runtime_config"`         // 运行配置
	RunState         string             `gorm:"column:run_state;type:varchar(16);not null" json:"run_state"`
	RunLastTime      *time.Time         `gorm:"column:run_last_time;type:datetime" json:"run_last_time"`
	RunNextTime      *time.Time         `gorm:"column:run_next_time;type:datetime" json:"run_next_time"`
	RunFailureReason string             `gorm:"column:run_failure_reason;type:varchar(255);not null" json:"run_failure_reason"`
	GenFrom          *string            `gorm:"column:gen_from;type:varchar(50);default:openapi;comment:创建来源，openapi生成的规则不可变" json:"gen_from"` // 创建来源，openapi生成的规则不可变
	Type             string             `gorm:"column:type;type:varchar(50);not null;comment:类型" json:"type"`                                  // 类型
	IsDeleted        int32              `gorm:"column:is_deleted;type:int;not null;comment:是否被删除" json:"is_deleted"`                           // 是否被删除
	CreatedBy        string             `gorm:"column:created_by;type:varchar(50);not null" json:"created_by"`
	CreateTime       *time.Time         `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime       *time.Time         `gorm:"column:update_time;type:datetime;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	Channels         []*AlarmChannelsDO `gorm:"foreignKey:ID;joinForeignKey:RuleID;joinReferences:ChannelID;many2many:alarm_rule_channels;references:ID" json:"channels"`
}

// TableName AlarmRulesDO's table name
func (*AlarmRulesDO) TableName() string {
	return TableNameAlarmRulesDO
}
